---
Dev_Mode: true
Server-Name-Dev: §c§lVortexMCPE
Server-Name: §c§lVortexMCPE
Hub-Command: §c§lVortexMCPE Teleporting...
Unknown-Command: §c§lVortexMCPE Unknown Command
max-caps: 800
interval: 60
item1: 0
item2: 0
item3: 0
item4: 0
...
